name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          echo "Running Robot Framework tests..."
          robot --outputdir test-results --exclude skip tests/ || FAILED=1

          if [ "$FAILED" = "1" ]; then
              echo "Some tests failed. Re-running failed tests..."
              robot --rerunfailed test-results/output.xml --outputdir test-results || true
          fi

          echo "Test execution completed."

      - name: Debug - List test results
        run: ls -R ${{ github.workspace }}/test-results/

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: ${{ github.workspace }}/test-results/
          retention-days: 3
